[package]
authors = ["Krishan Wyse <kwysek@gmail.com>"]
name = "scintillis"
version = "0.1.0"

[dependencies]
clap = "2.17.1"
glium = "0.15.0"
serde = "0.8.17"
serde_derive = "0.8.17"
serde_yaml = "0.5.0"
